# Generated by Django 5.1.4 on 2025-02-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFromHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LessonFromHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('room', models.CharField(max_length=150)),
                ('lesson_type', models.CharField(max_length=4)),
                ('groups', models.ManyToManyField(to='edu_resources.edugroup')),
                ('teachers', models.ManyToManyField(to='edu_resources.teacherfromhand')),
            ],
        ),
    ]
