# Generated by Django 5.1.4 on 2025-02-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_resources', '0002_teacherfromhand_lessonfromhand'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonfromhand',
            name='file_name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
