# Generated by Django 5.1.4 on 2025-02-08 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_resources', '0003_lessonfromhand_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonfromhand',
            name='groups',
        ),
        migrations.AddField(
            model_name='lessonfromhand',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_resources.edugroup'),
        ),
    ]
