# Generated by Django 5.1.4 on 2025-02-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_resources', '0004_remove_lessonfromhand_groups_lessonfromhand_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='edugroup',
            name='ms_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='edugroup',
            name='course',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='edugroup',
            name='form',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='edugroup',
            name='naprav',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='edugroup',
            name='profile',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='edugroup',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='edugroup',
            name='work_plan',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
