# Generated by Django 5.1.4 on 2025-02-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_resources', '0005_edugroup_ms_id_alter_edugroup_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonfromhand',
            name='discipline',
            field=models.CharField(max_length=250),
        ),
    ]
