# Generated by Django 5.1.4 on 2025-02-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_resources', '0006_alter_lessonfromhand_discipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonfromhand',
            name='group',
        ),
        migrations.AddField(
            model_name='lessonfromhand',
            name='groups',
            field=models.ManyToManyField(to='edu_resources.edugroup'),
        ),
    ]
