# Generated by Django 5.1.4 on 2025-02-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_resources', '0008_alter_lessonfromhand_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherfromhand',
            old_name='shortname',
            new_name='name',
        ),
    ]
