# Generated by Django 5.1.4 on 2025-02-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_resources', '0009_rename_shortname_teacherfromhand_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonfromhand',
            options={'ordering': ['date', 'start_time']},
        ),
    ]
