# Generated by Django 5.1.4 on 2025-02-09 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_resources', '0012_alter_room_location_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_resources.teacherfromhand'),
        ),
    ]
